#include "bass_sym.h"
#include "log.h"

void BASS_GetCPU(){FATAL("Direct calling dummy of BASS_GetCPU");}
void BASS_SampleFree(){FATAL("Direct calling dummy of BASS_SampleFree");}
void BASS_SampleSetInfo(){FATAL("Direct calling dummy of BASS_SampleSetInfo");}
void BASS_SampleGetChannels(){FATAL("Direct calling dummy of BASS_SampleGetChannels");}
void BASS_SampleStop(){FATAL("Direct calling dummy of BASS_SampleStop");}
void BASS_StreamFree(){FATAL("Direct calling dummy of BASS_StreamFree");}
void BASS_ChannelGetTags(){FATAL("Direct calling dummy of BASS_ChannelGetTags");}
void BASS_StreamGetFilePosition(){FATAL("Direct calling dummy of BASS_StreamGetFilePosition");}
void BASS_StreamPutFileData(){FATAL("Direct calling dummy of BASS_StreamPutFileData");}
void BASS_MusicFree(){FATAL("Direct calling dummy of BASS_MusicFree");}
void BASS_ChannelIsActive(){FATAL("Direct calling dummy of BASS_ChannelIsActive");}
void BASS_ChannelGetDevice(){FATAL("Direct calling dummy of BASS_ChannelGetDevice");}
void BASS_ChannelBytes2Seconds(){FATAL("Direct calling dummy of BASS_ChannelBytes2Seconds");}
void BASS_ChannelSeconds2Bytes(){FATAL("Direct calling dummy of BASS_ChannelSeconds2Bytes");}
void BASS_ChannelIsSliding(){FATAL("Direct calling dummy of BASS_ChannelIsSliding");}
void BASS_ChannelGetPosition(){FATAL("Direct calling dummy of BASS_ChannelGetPosition");}
void BASS_ChannelGetLength(){FATAL("Direct calling dummy of BASS_ChannelGetLength");}
void BASS_ChannelLock(){FATAL("Direct calling dummy of BASS_ChannelLock");}
void BASS_ChannelSetSync(){FATAL("Direct calling dummy of BASS_ChannelSetSync");}
void BASS_ChannelRemoveSync(){FATAL("Direct calling dummy of BASS_ChannelRemoveSync");}
void BASS_ChannelSetDSP(){FATAL("Direct calling dummy of BASS_ChannelSetDSP");}
void BASS_ChannelRemoveDSP(){FATAL("Direct calling dummy of BASS_ChannelRemoveDSP");}
void BASS_ChannelGet3DPosition(){FATAL("Direct calling dummy of BASS_ChannelGet3DPosition");}
void BASS_ChannelSetLink(){FATAL("Direct calling dummy of BASS_ChannelSetLink");}
void BASS_ChannelRemoveLink(){FATAL("Direct calling dummy of BASS_ChannelRemoveLink");}
void BASS_ChannelSetFX(){FATAL("Direct calling dummy of BASS_ChannelSetFX");}
void BASS_ChannelRemoveFX(){FATAL("Direct calling dummy of BASS_ChannelRemoveFX");}
void BASS_FXSetParameters(){FATAL("Direct calling dummy of BASS_FXSetParameters");}
void BASS_FXGetParameters(){FATAL("Direct calling dummy of BASS_FXGetParameters");}
void BASS_FXReset(){FATAL("Direct calling dummy of BASS_FXReset");}
void BASS_FXSetPriority(){FATAL("Direct calling dummy of BASS_FXSetPriority");}
void BASS_Free(){FATAL("Direct calling dummy of BASS_Free");}
void BASS_StreamCreate(){FATAL("Direct calling dummy of BASS_StreamCreate");}
void BASS_SampleGetData(){FATAL("Direct calling dummy of BASS_SampleGetData");}
void BASS_SampleSetData(){FATAL("Direct calling dummy of BASS_SampleSetData");}
void BASS_SampleGetInfo(){FATAL("Direct calling dummy of BASS_SampleGetInfo");}
void BASS_ChannelGetInfo(){FATAL("Direct calling dummy of BASS_ChannelGetInfo");}
void BASS_ChannelFlags(){FATAL("Direct calling dummy of BASS_ChannelFlags");}
void BASS_MusicLoad(){FATAL("Direct calling dummy of BASS_MusicLoad");}
void BASS_ChannelSet3DAttributes(){FATAL("Direct calling dummy of BASS_ChannelSet3DAttributes");}
void BASS_SampleCreate(){FATAL("Direct calling dummy of BASS_SampleCreate");}
void BASS_ChannelGet3DAttributes(){FATAL("Direct calling dummy of BASS_ChannelGet3DAttributes");}
void BASS_ChannelSet3DPosition(){FATAL("Direct calling dummy of BASS_ChannelSet3DPosition");}
void BASS_SampleGetChannel(){FATAL("Direct calling dummy of BASS_SampleGetChannel");}
void BASS_Init(){FATAL("Direct calling dummy of BASS_Init");}
void BASS_ChannelStop(){FATAL("Direct calling dummy of BASS_ChannelStop");}
void BASS_ChannelPause(){FATAL("Direct calling dummy of BASS_ChannelPause");}
void BASS_Update(){FATAL("Direct calling dummy of BASS_Update");}
void BASS_ChannelSetPosition(){FATAL("Direct calling dummy of BASS_ChannelSetPosition");}
void BASS_ChannelPlay(){FATAL("Direct calling dummy of BASS_ChannelPlay");}
void BASS_StreamPutData(){FATAL("Direct calling dummy of BASS_StreamPutData");}
void BASS_ChannelUpdate(){FATAL("Direct calling dummy of BASS_ChannelUpdate");}
void BASS_ChannelGetData(){FATAL("Direct calling dummy of BASS_ChannelGetData");}
void BASS_ChannelGetLevelEx(){FATAL("Direct calling dummy of BASS_ChannelGetLevelEx");}
void BASS_ChannelGetLevel(){FATAL("Direct calling dummy of BASS_ChannelGetLevel");}
void BASS_ChannelSetDevice(){FATAL("Direct calling dummy of BASS_ChannelSetDevice");}
void BASS_SetDevice(){FATAL("Direct calling dummy of BASS_SetDevice");}
void BASS_GetDevice(){FATAL("Direct calling dummy of BASS_GetDevice");}
void BASS_GetDeviceInfo(){FATAL("Direct calling dummy of BASS_GetDeviceInfo");}
void BASS_GetInfo(){FATAL("Direct calling dummy of BASS_GetInfo");}
void BASS_Start(){FATAL("Direct calling dummy of BASS_Start");}
void BASS_Stop(){FATAL("Direct calling dummy of BASS_Stop");}
void BASS_Pause(){FATAL("Direct calling dummy of BASS_Pause");}
void BASS_IsStarted(){FATAL("Direct calling dummy of BASS_IsStarted");}
void BASS_SetVolume(){FATAL("Direct calling dummy of BASS_SetVolume");}
void BASS_GetVolume(){FATAL("Direct calling dummy of BASS_GetVolume");}
void BASS_Set3DFactors(){FATAL("Direct calling dummy of BASS_Set3DFactors");}
void BASS_Get3DFactors(){FATAL("Direct calling dummy of BASS_Get3DFactors");}
void BASS_Set3DPosition(){FATAL("Direct calling dummy of BASS_Set3DPosition");}
void BASS_Get3DPosition(){FATAL("Direct calling dummy of BASS_Get3DPosition");}
void BASS_Apply3D(){FATAL("Direct calling dummy of BASS_Apply3D");}
void BASS_RecordFree(){FATAL("Direct calling dummy of BASS_RecordFree");}
void BASS_RecordInit(){FATAL("Direct calling dummy of BASS_RecordInit");}
void BASS_RecordSetDevice(){FATAL("Direct calling dummy of BASS_RecordSetDevice");}
void BASS_RecordGetDevice(){FATAL("Direct calling dummy of BASS_RecordGetDevice");}
void BASS_RecordGetDeviceInfo(){FATAL("Direct calling dummy of BASS_RecordGetDeviceInfo");}
void BASS_RecordGetInfo(){FATAL("Direct calling dummy of BASS_RecordGetInfo");}
void BASS_RecordGetInputName(){FATAL("Direct calling dummy of BASS_RecordGetInputName");}
void BASS_RecordSetInput(){FATAL("Direct calling dummy of BASS_RecordSetInput");}
void BASS_RecordGetInput(){FATAL("Direct calling dummy of BASS_RecordGetInput");}
void BASS_RecordStart(){FATAL("Direct calling dummy of BASS_RecordStart");}
void BASS_GetVersion(){FATAL("Direct calling dummy of BASS_GetVersion");}
void BASS_ErrorGetCode(){FATAL("Direct calling dummy of BASS_ErrorGetCode");}
void BASS_ChannelSetAttribute(){FATAL("Direct calling dummy of BASS_ChannelSetAttribute");}
void BASS_ChannelGetAttribute(){FATAL("Direct calling dummy of BASS_ChannelGetAttribute");}
void BASS_ChannelSlideAttribute(){FATAL("Direct calling dummy of BASS_ChannelSlideAttribute");}
void BASS_ChannelSetAttributeEx(){FATAL("Direct calling dummy of BASS_ChannelSetAttributeEx");}
void BASS_ChannelGetAttributeEx(){FATAL("Direct calling dummy of BASS_ChannelGetAttributeEx");}
void BASS_SetConfig(){FATAL("Direct calling dummy of BASS_SetConfig");}
void BASS_GetConfig(){FATAL("Direct calling dummy of BASS_GetConfig");}
void BASS_StreamCreateURL(){FATAL("Direct calling dummy of BASS_StreamCreateURL");}
void BASS_StreamCreateFile(){FATAL("Direct calling dummy of BASS_StreamCreateFile");}
void BASS_SampleLoad(){FATAL("Direct calling dummy of BASS_SampleLoad");}
void BASS_StreamCreateFileUser(){FATAL("Direct calling dummy of BASS_StreamCreateFileUser");}
void BASS_SetConfigPtr(){FATAL("Direct calling dummy of BASS_SetConfigPtr");}
void BASS_GetConfigPtr(){FATAL("Direct calling dummy of BASS_GetConfigPtr");}
void BASS_PluginLoad(){FATAL("Direct calling dummy of BASS_PluginLoad");}
void BASS_PluginFree(){FATAL("Direct calling dummy of BASS_PluginFree");}
void BASS_PluginGetInfo(){FATAL("Direct calling dummy of BASS_PluginGetInfo");}
